# Specifier-owned regression: catalog loading must not enforce download support.
cmake_minimum_required(VERSION 3.12)
if(NOT REPO OR NOT CASE OR NOT SCRATCH)
    message(FATAL_ERROR "Pass REPO, CASE and SCRATCH")
endif()
include("${REPO}/cmake/versions.cmake")
include("${REPO}/cmake/deps/PackageManager.cmake")
include("${REPO}/cmake/deps/strategies/ProvidedPackageManager.cmake")
set(DEPS_PROVIDED_DIR "${SCRATCH}/downloads")
set(DEPS_OFFLINE ON)
set(USE_ONNX_RUNTIME OFF)

if(CASE STREQUAL "linux-x64")
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
    set(expected "onnxruntime-linux-x64-${ONNX_RUNTIME_VERSION}.tgz")
elseif(CASE STREQUAL "linux-arm64")
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
    set(expected "onnxruntime-linux-aarch64-${ONNX_RUNTIME_VERSION}.tgz")
elseif(CASE STREQUAL "windows-x64")
    set(CMAKE_SYSTEM_NAME Windows)
    set(CMAKE_SYSTEM_PROCESSOR AMD64)
    set(expected "onnxruntime-win-x64-${ONNX_RUNTIME_VERSION}.zip")
elseif(CASE STREQUAL "windows-arm64")
    set(CMAKE_SYSTEM_NAME Windows)
    set(CMAKE_SYSTEM_PROCESSOR ARM64)
    set(expected "onnxruntime-win-arm64-${ONNX_RUNTIME_VERSION}.zip")
elseif(CASE MATCHES "^darwin")
    set(CMAKE_SYSTEM_NAME Darwin)
    set(CMAKE_SYSTEM_PROCESSOR arm64)
    set(CMAKE_SHARED_LIBRARY_SUFFIX .dylib)
else()
    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR riscv64)
    set(CMAKE_SHARED_LIBRARY_SUFFIX .so)
endif()
include("${REPO}/cmake/deps/packages/OnnxRuntime.cmake")
deps_decl_get(OnnxRuntime CONAN conan)
deps_decl_get(OnnxRuntime VCPKG vcpkg)
if(NOT conan OR NOT vcpkg)
    message(FATAL_ERROR "External providers must remain declared")
endif()
deps_decl_get(OnnxRuntime PROVIDED_URL url)
deps_decl_get(OnnxRuntime PROVIDED_ACQUIRE acquire)
if(expected)
    get_filename_component(archive "${url}" NAME)
    if(NOT archive STREQUAL expected OR NOT acquire STREQUAL "DOWNLOAD")
        message(FATAL_ERROR "Supported archive changed: ${archive}, ${acquire}")
    endif()
else()
    set(DEPS_OFFLINE OFF)
    deps_provided_can_resolve(OnnxRuntime available)
    if(available)
        message(FATAL_ERROR "Unsupported platform must not attempt a download")
    endif()
endif()

if(CASE MATCHES "root$")
    set(ONNXRUNTIME_ROOTDIR "${SCRATCH}/prefix")
    file(MAKE_DIRECTORY "${ONNXRUNTIME_ROOTDIR}/include" "${ONNXRUNTIME_ROOTDIR}/lib")
    file(WRITE "${ONNXRUNTIME_ROOTDIR}/include/onnxruntime_cxx_api.h" "// fixture\n")
    if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(library "lib/libonnxruntime.dylib")
    else()
        set(library "lib/libonnxruntime.so.${ONNX_RUNTIME_VERSION}")
    endif()
    file(WRITE "${ONNXRUNTIME_ROOTDIR}/${library}" "fixture; not a link test\n")
    set(DEPS_OFFLINE ON)
    deps_provided_can_resolve(OnnxRuntime available)
    if(NOT available)
        message(FATAL_ERROR "Explicit ROOT must be reachable")
    endif()
    deps_provided_resolve(OnnxRuntime)
    deps_get_rec(OnnxRuntime LIBRARIES resolved)
    if(NOT resolved STREQUAL "${ONNXRUNTIME_ROOTDIR}/${library}")
        message(FATAL_ERROR "Wrong root library: ${resolved}")
    endif()
endif()
message(STATUS "PASS catalog ${CASE}")
