#!/usr/bin/env python3
"""Summarise run_profile.sh's raw artifacts into the metrics protocol.md requires.

Usage: summarize_profile.py <results-dir>  > summary.md

Every number printed here is computed from a file under <results-dir>; nothing is
estimated. A metric whose input is missing is printed as UNRUN, never as zero.
"""
import glob
import json
import os
import re
import statistics
import sys

OUT = sys.argv[1]
FRAMES = {"image": 1, "5f": 5, "30f": 30, "60f": 60}


def elapsed_seconds(text):
    m = re.search(r"Elapsed \(wall clock\) time.*?: ([\d:.]+)", text)
    parts = [float(p) for p in m.group(1).split(":")]
    seconds = 0.0
    for p in parts:
        seconds = seconds * 60 + p
    return seconds


def field(text, name, cast=float):
    m = re.search(re.escape(name) + r": ([\d.]+)%?", text)
    return cast(m.group(1)) if m else None


def dist(values):
    if not values:
        return None
    mean = statistics.fmean(values)
    sd = statistics.stdev(values) if len(values) > 1 else 0.0
    return {
        "n": len(values), "min": min(values), "max": max(values),
        "median": statistics.median(values), "mean": mean, "sd": sd,
        "cv": 100 * sd / mean if mean else 0.0,
    }


def fmt(d, unit, scale=1.0):
    if d is None:
        return "UNRUN"
    flag = " **unstable (CV > 5 %)**" if d["cv"] > 5 else ""
    return (f"n={d['n']} median {d['median'] * scale:.3f} {unit}, mean {d['mean'] * scale:.3f}, "
            f"min {d['min'] * scale:.3f}, max {d['max'] * scale:.3f}, sd {d['sd'] * scale:.3f}, "
            f"CV {d['cv']:.2f} %{flag}")


print("# Profiling summary (generated by summarize_profile.py)\n")
with open(os.path.join(OUT, "status.txt")) as f:
    print("## Step status\n\n```\n" + f.read() + "```\n")

# --- Timing --------------------------------------------------------------------
print("## Timing (`/usr/bin/time -v`, pinned)\n")
print("| Set | Elapsed | Max RSS | CPU % | FPS (frames / median elapsed) |")
print("|-----|---------|---------|-------|------|")
medians = {}
for tag in ["A-image", "B-image", "A-30f", "B-30f", "C-30f", "B-60f",
            "A-image-set2", "B-image-set2", "A-30f-set2", "B-30f-set2", "C-30f-set2", "B-60f-set2"]:
    files = sorted(p for p in glob.glob(os.path.join(OUT, "timing", f"{tag}-*.time"))
                   if re.fullmatch(re.escape(tag) + r"-\d+\.time", os.path.basename(p)))
    if not files and tag.endswith("-set2"):
        continue
    if not files:
        print(f"| {tag} | UNRUN | | | |")
        continue
    texts = [open(p).read() for p in files]
    el = dist([elapsed_seconds(t) for t in texts])
    rss = dist([field(t, "Maximum resident set size (kbytes)") for t in texts])
    cpu = dist([field(t, "Percent of CPU this job got") for t in texts])
    frames = FRAMES[tag.split("-")[1]]
    if tag.endswith("-set2"):
        tag_key = tag[:-5]
        print(f"| {tag} | {fmt(el, 's')} | median {rss['median'] / 1024:.1f} MiB | median {cpu['median']:.0f} | {frames / el['median']:.3f} |")
        continue
    medians[tag] = el["median"]
    print(f"| {tag} | {fmt(el, 's')} | median {rss['median'] / 1024:.1f} MiB, max {rss['max'] / 1024:.1f} MiB "
          f"({rss['max']:.0f} KiB) | median {cpu['median']:.0f} | {frames / el['median']:.3f} |")
print()
if "B-30f" in medians and "B-60f" in medians:
    slope = (medians["B-60f"] - medians["B-30f"]) / 30
    fixed = medians["B-30f"] - 30 * slope
    print(f"Arm B per-frame cost from the 30f→60f slope: **{slope:.3f} s/frame**; "
          f"fixed (startup) cost: **{fixed:.3f} s**.\n")
if "A-30f" in medians and "B-30f" in medians:
    print(f"Arm A vs arm B, 30f median: {medians['A-30f']:.3f} s vs {medians['B-30f']:.3f} s "
          "(compare against the CVs above before calling it a difference).\n")
if "C-30f" in medians and "B-30f" in medians:
    print(f"Counterfactual C (IntraOpNumThreads = pinned cores) vs shipped B, 30f median: "
          f"{medians['C-30f']:.3f} s vs {medians['B-30f']:.3f} s "
          f"({medians['B-30f'] / medians['C-30f']:.2f}x).\n")

# --- perf stat -----------------------------------------------------------------
print("## `perf stat` (30-frame video, arm B, pinned)\n")
for group in ["sw", "ipc", "branch", "cache"]:
    files = sorted(glob.glob(os.path.join(OUT, "perf", f"stat-{group}-*.csv")))
    values, ratios, unsupported = {}, {}, False
    for p in files:
        for line in open(p):
            cols = line.strip().split(",")
            if len(cols) < 3 or line.startswith("#") or not cols[2]:
                continue
            if cols[0].startswith("<"):
                unsupported = True
                continue
            event = cols[2]
            values.setdefault(event, []).append(float(cols[0]))
            if len(cols) > 4 and cols[4]:
                ratios.setdefault(event, []).append(float(cols[4]))
    if unsupported or not values:
        print(f"- **{group}**: UNRUN — counters `<not supported>` on this host (`perf/stat-{group}-1.csv`)")
        continue
    for event, vals in values.items():
        r = min(ratios.get(event, [100.0]))
        print(f"- {event}: {fmt(dist(vals), '')}; min enabled/running {r:.1f} %"
              + (" **multiplexed (< 90 %)**" if r < 90 else ""))
    if group == "sw" and "task-clock" in values and "B-30f" in medians:
        tc = statistics.median(values["task-clock"]) / 1000
        print(f"- average utilised cores = task-clock / elapsed = {tc:.2f} s / {medians['B-30f']:.2f} s "
              f"= **{tc / medians['B-30f']:.2f}**")
        for ev in ["context-switches", "cpu-migrations", "page-faults"]:
            if ev in values:
                print(f"- {ev} per frame: {statistics.median(values[ev]) / 30:.1f}")
    if group == "ipc" and {"cycles", "instructions"} <= values.keys():
        print(f"- IPC: **{statistics.median(values['instructions']) / statistics.median(values['cycles']):.3f}**")
    if group == "branch" and {"branches", "branch-misses"} <= values.keys():
        print(f"- branch miss: **{100 * statistics.median(values['branch-misses']) / statistics.median(values['branches']):.3f} %**")
    if group == "cache" and {"cache-references", "cache-misses"} <= values.keys():
        print(f"- generic cache miss: **{100 * statistics.median(values['cache-misses']) / statistics.median(values['cache-references']):.3f} %**")
print()

# --- perf record ---------------------------------------------------------------
print("## `perf record` call graph\n")
self_path = os.path.join(OUT, "perf", "report-self.txt")
if os.path.exists(self_path) and os.path.getsize(self_path):
    text = open(self_path).read()
    samples = re.search(r"# Samples: (\S+) of event '([^']+)'", text)
    lost = re.search(r"# Total Lost Samples: (\d+)", text)
    rows = re.findall(r"^\s+([\d.]+)%\s+(\[.\])\s+(.+?)\s{2,}(\S+)\s*$", text, re.M)
    unresolved = sum(float(p) for p, _, sym, _ in rows if sym.startswith("0x") or "[unknown]" in sym)
    print(f"- event `{samples.group(2) if samples else '?'}`, samples {samples.group(1) if samples else '?'}, "
          f"lost {lost.group(1) if lost else '0'}, unresolved-symbol share {unresolved:.2f} %"
          + (" **> 10 %: attribution must be fixed**" if unresolved > 10 else ""))
    print("\nTop ten symbols, Self:\n\n| Self % | Symbol | DSO |\n|---|---|---|")
    for p, _, sym, dso in rows[:10]:
        print(f"| {p} | `{sym[:90]}` | {dso} |")
    ch = open(os.path.join(OUT, "perf", "report-children.txt")).read()
    crow = re.findall(r"^\s+([\d.]+)%\s+([\d.]+)%\s+(\[.\])\s+(.+?)\s{2,}(\S+)\s*$", ch, re.M)
    print("\nTop ten symbols, Children:\n\n| Children % | Self % | Symbol | DSO |\n|---|---|---|---|")
    for c, s, _, sym, dso in crow[:10]:
        print(f"| {c} | {s} | `{sym[:90]}` | {dso} |")
    dso_text = open(os.path.join(OUT, "perf", "report-dso.txt")).read()
    print("\nBy DSO:\n")
    for p, dso in re.findall(r"^\s+([\d.]+)%\s+(\S+)\s*$", dso_text, re.M)[:8]:
        print(f"- {dso}: {p} %")
else:
    print("UNRUN — `perf/report-self.txt` missing; see `perf/record.log`")
print()

# --- Memory ----------------------------------------------------------------------
print("## Memory\n")
for name in ["massif-image", "massif-5f"]:
    out = os.path.join(OUT, "memory", f"{name}.out")
    if not os.path.exists(out):
        print(f"- {name}: UNRUN")
        continue
    snaps = []
    for block in open(out).read().split("snapshot=")[1:]:
        get = lambda k: int(re.search(rf"{k}=(\d+)", block).group(1))
        snaps.append((get("mem_heap_B") + get("mem_heap_extra_B") + get("mem_stacks_B"),
                      get("mem_heap_B"), get("mem_heap_extra_B"), get("mem_stacks_B")))
    total, heap, extra, stacks = max(snaps)
    mib = lambda b: b / 1048576
    print(f"- **{name}** peak: heap {mib(heap):.1f} MiB + extra {mib(extra):.1f} MiB + stacks {mib(stacks):.2f} MiB "
          f"= {mib(total):.1f} MiB ({heap} B heap)")
    txt = open(os.path.join(OUT, "memory", f"{name}.txt")).read()
    peak = re.search(r"Detailed snapshots: \[.*?(\d+) \(peak\)", txt)
    if peak:
        sect = re.search(rf"^\s+{peak.group(1)}\s.*?\n(.*?)(?:^-{{20,}}|\Z)", txt, re.M | re.S)
        tree = [l for l in (sect.group(1) if sect else "").splitlines() if re.match(r"^[ |]*->", l)]
        print(f"  - peak snapshot {peak.group(1)} allocation owners (top level of the ms_print tree):")
        for line in [l for l in tree if re.match(r"^ ?->", l)][:8]:
            print(f"    - `{line.strip()[:150]}`")
mc = os.path.join(OUT, "memory", "memcheck.log")
if os.path.exists(mc):
    t = open(mc).read()
    for k in ["definitely lost", "indirectly lost", "possibly lost", "still reachable", "suppressed"]:
        m = re.search(rf"{k}: ([\d,]+) bytes in ([\d,]+) blocks", t)
        print(f"- Memcheck {k}: {m.group(1) + ' bytes in ' + m.group(2) + ' blocks' if m else 'not reported'}")
    e = re.search(r"ERROR SUMMARY: (\d+) errors", t)
    x = re.search(r"^exit: (\d+)", t, re.M)  # not "in use at exit: N bytes"
    print(f"- Memcheck errors: {e.group(1) if e else '?'}; exit {x.group(1) if x else '?'}")
print()

# --- Benchmarks ------------------------------------------------------------------
print("## Google Benchmark (`build-bench`, Release, `-DWERROR=ON`, 5 repetitions, pinned)\n")
bj = os.path.join(OUT, "bench", "benchmarks.json")
if os.path.exists(bj):
    data = json.load(open(bj))
    agg = {}
    for b in data["benchmarks"]:
        if b.get("run_type") == "aggregate":
            agg.setdefault(b["run_name"], {})[b["aggregate_name"]] = b
        else:
            agg.setdefault(b["run_name"], {}).setdefault("iterations", b["iterations"])
    print("| Benchmark | real mean | real CV | CPU mean | CPU CV | iterations |\n|---|---|---|---|---|---|")
    for name, a in agg.items():
        if "mean" not in a:
            continue
        m, unit = a["mean"], a["mean"]["time_unit"]
        cvr = a.get("cv", {}).get("real_time", 0) * (100 if a.get("cv", {}).get("aggregate_unit") == "percentage" else 1)
        cvc = a.get("cv", {}).get("cpu_time", 0) * (100 if a.get("cv", {}).get("aggregate_unit") == "percentage" else 1)
        print(f"| {name} | {m['real_time']:.1f} {unit} | {cvr:.2f} % | {m['cpu_time']:.1f} {unit} | {cvc:.2f} % | {a.get('iterations', '?')} |")
    ctx = data.get("context", {})
    print(f"\nContext: {ctx.get('num_cpus')} CPUs @ {ctx.get('mhz_per_cpu')} MHz, "
          f"library build {ctx.get('library_build_type')}, scaling {ctx.get('cpu_scaling_enabled')}")
else:
    print("UNRUN — benchmarks.json missing")
